### PR TITLE
Feature/cloud 1738 skip sonar

### PR DESCRIPTION
**Pull request by naveen-variant**
# Description

Skip sonar run in case of re-run.

Fixes [#31](https://usxtech.atlassian.net/browse/CLOUD-1738)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

[Demo Flask app](https://github.com/variant-inc/demo-python-flask-variant-api/tree/test/master-postgress)

```yaml
Test Case 1: Sonar Should run
  1. Navigate to demo app branch create a commit.
  2. Should trigger sonar run. Also verify in sonar if results are pushed.

Result
  - Expected: See sonar is run on the commit.
  - Actual: 

Test Case 2: Skip sonar run
  1. Navigate to actions and pick the run previously created.
  2. Re-run the build, it should trigger sonar run as sonar has already been run on this commit.

Result
  - Expected: See sonar is skipped, lazy action step logs should say sonar is skipped.
```

- [ ] Unit Tests
- [x] Sanity Testing

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by salyateem13** [comment]
https://github.com/variant-inc/demo-python-flask-variant-api/runs/6728833895?check_suite_focus=true#step:5:555

**Comment by salyateem13** [comment]
Sonar scan is being executed after multiple successful scans

**Review by genghis-tuan — COMMENTED** [review]
I added an inline comment in **actions-collection** PR no: 28.

There seems to be an issue with comparing an object to a string and that may be causing the failure of detecting when to skip sonar. The code suggestion is here for ref:

I wonder if this query is causing the issue with failed testing. As is, It expands the entire `commit` object and tries to compare that to`$env:GITHUB_SHA`.  If `$env:GITHUB_SHA` is also an object, then maybe we can just take the sha like shown below?

Can we try updating with:
```
$CommitSha = ($Response.branches | Where-Object {
    $_.name -like $env:GITHUB_REF_NAME
}  | Select-Object -First 1).commit.sha
```

**Comment by naveen-variant** [comment]
> I added an inline comment in **actions-collection** PR no: 28.
> 
> There seems to be an issue with comparing an object to a string and that may be causing the failure of detecting when to skip sonar. The code suggestion is here for ref:
> 
> I wonder if this query is causing the issue with failed testing. As is, It expands the entire `commit` object and tries to compare that to`$env:GITHUB_SHA`. If `$env:GITHUB_SHA` is also an object, then maybe we can just take the sha like shown below?
> 
> Can we try updating with:
> 
> ```
> $CommitSha = ($Response.branches | Where-Object {
>     $_.name -like $env:GITHUB_REF_NAME
> }  | Select-Object -First 1).commit.sha
> ```

@genghis-tuan It was because image tag is changed for test-latest. Tested it again as below

With new commit below are the logs

```bash
+ echo 'Skip sonar run: False'
Skip sonar run: False
End: Check sonar run
---Start: Sonar Scan
```
When re-run the same commit 
```bash
Skip sonar run: True
End: Check sonar run
Skipping sonar run
```

**Review by genghis-tuan — APPROVED** [review]
Tested successfully https://github.com/variant-inc/demo-python-flask-variant-api/runs/6780007553?check_suite_focus=true

4 runs of the same build.
1. Pass: sonar was run and posted
2. Pass: sonar was skipped
3. Pass: sonar was skipped
4. Pass: sonar was skipped.

Still need to update the actions-collections branch from the dev branch and change the python-actions image tag.

**Review by genghis-tuan — APPROVED** [review]

**Review by jahnavimaddi — APPROVED** [review]

**Pull request merged**
